In [1]:
import pandas as pd

In [2]:
import numpy as np

Importar valores del CSV

In [3]:
df = pd.read_csv("personas_sucio.csv")

In [19]:
df = df.copy()

EJERCICIOS

- No haya valores nulos

In [4]:
df.fillna("YA NO HAY NULOS")

     nombre             edad     ciudad               email   fecha_registro
0     Ana                 25    madrid      ana@example.com       2024-01-10
1      Luis               30    Sevilla    luis(at)mail.com       10/01/2024
2     Marta  YA NO HAY NULOS   VALENCIA   marta@example.com       2024-02-15
3    Pedro        veintiocho  Barcelona    pedroexample.com  YA NO HAY NULOS
4     lucía               22     Madrid   lucia@example.com        2024-3-05
5       ANA               25        MAD     ana@example.com       2024/01/10
6     Sofia              27     sevilla     YA NO HAY NULOS       2024-05-20
7    Miguel               29        Sev     miguel@mail.com       2024-06-01
8      Juan  YA NO HAY NULOS     madrid      juan@@mail.com       2024-02-30
9     Laura              31    Valéncia   laura@example.com       2024-07-10
10  Antonio               35     Madrid    antonio@mail.com       2023-11-25
11    María  YA NO HAY NULOS    Sevilla      maria@mail.com       2024-01-15
12     Raúl          treinta   Valencia   raul@@example.com       2024-05-12
13     Eva                28  barcelona         eva@example       2024-04-05
14   Daniel               33     Madrid  daniel@example.com       2024-02-29
15   Isabel               27       Sev.     isabel@mail.com       2024-03-10
16  Alberto               40   Valencia    alberto@mail.com       2024/06/12
17   Carmen  YA NO HAY NULOS   Valéncia  carmen@example.com       2024-07-01
18    Pablo               19     MADRID       pablo@mailcom       2024-05-30
19   Teresa               25   Sevilla     teresa@ mail.com       2024-02-20

- Todos los nombres tengan la primera letra en mayúscula y el resto minúsculas

In [5]:
df["nombre"] = df["nombre"].str.strip().str.title()

In [6]:
df

     nombre        edad     ciudad               email fecha_registro
0       Ana          25    madrid      ana@example.com     2024-01-10
1      Luis          30    Sevilla    luis(at)mail.com     10/01/2024
2     Marta         NaN   VALENCIA   marta@example.com     2024-02-15
3     Pedro  veintiocho  Barcelona    pedroexample.com            NaN
4     Lucía          22     Madrid   lucia@example.com      2024-3-05
5       Ana          25        MAD     ana@example.com     2024/01/10
6     Sofia         27     sevilla                 NaN     2024-05-20
7    Miguel          29        Sev     miguel@mail.com     2024-06-01
8      Juan         NaN     madrid      juan@@mail.com     2024-02-30
9     Laura         31    Valéncia   laura@example.com     2024-07-10
10  Antonio          35     Madrid    antonio@mail.com     2023-11-25
11    María         NaN    Sevilla      maria@mail.com     2024-01-15
12     Raúl     treinta   Valencia   raul@@example.com     2024-05-12
13      Eva          28  barcelona         eva@example     2024-04-05
14   Daniel          33     Madrid  daniel@example.com     2024-02-29
15   Isabel          27       Sev.     isabel@mail.com     2024-03-10
16  Alberto          40   Valencia    alberto@mail.com     2024/06/12
17   Carmen         NaN   Valéncia  carmen@example.com     2024-07-01
18    Pablo          19     MADRID       pablo@mailcom     2024-05-30
19   Teresa          25   Sevilla     teresa@ mail.com     2024-02-20

- Todas las edades estén en formato númerico (las que sean 0 o NaN, sustituirlas por el valor medio de la columna EDAD).

In [7]:
df["edad"] = pd.to_numeric(df["edad"], errors="coerce")

In [8]:
df

     nombre  edad     ciudad               email fecha_registro
0       Ana  25.0    madrid      ana@example.com     2024-01-10
1      Luis  30.0    Sevilla    luis(at)mail.com     10/01/2024
2     Marta   NaN   VALENCIA   marta@example.com     2024-02-15
3     Pedro   NaN  Barcelona    pedroexample.com            NaN
4     Lucía  22.0     Madrid   lucia@example.com      2024-3-05
5       Ana  25.0        MAD     ana@example.com     2024/01/10
6     Sofia  27.0    sevilla                 NaN     2024-05-20
7    Miguel  29.0        Sev     miguel@mail.com     2024-06-01
8      Juan   NaN     madrid      juan@@mail.com     2024-02-30
9     Laura  31.0   Valéncia   laura@example.com     2024-07-10
10  Antonio  35.0     Madrid    antonio@mail.com     2023-11-25
11    María   NaN    Sevilla      maria@mail.com     2024-01-15
12     Raúl   NaN   Valencia   raul@@example.com     2024-05-12
13      Eva  28.0  barcelona         eva@example     2024-04-05
14   Daniel  33.0     Madrid  daniel@example.com     2024-02-29
15   Isabel  27.0       Sev.     isabel@mail.com     2024-03-10
16  Alberto  40.0   Valencia    alberto@mail.com     2024/06/12
17   Carmen   NaN   Valéncia  carmen@example.com     2024-07-01
18    Pablo  19.0     MADRID       pablo@mailcom     2024-05-30
19   Teresa  25.0   Sevilla     teresa@ mail.com     2024-02-20

In [9]:
df["edad"] = df["edad"].replace(0, np.nan)

In [10]:
df

     nombre  edad     ciudad               email fecha_registro
0       Ana  25.0    madrid      ana@example.com     2024-01-10
1      Luis  30.0    Sevilla    luis(at)mail.com     10/01/2024
2     Marta   NaN   VALENCIA   marta@example.com     2024-02-15
3     Pedro   NaN  Barcelona    pedroexample.com            NaN
4     Lucía  22.0     Madrid   lucia@example.com      2024-3-05
5       Ana  25.0        MAD     ana@example.com     2024/01/10
6     Sofia  27.0    sevilla                 NaN     2024-05-20
7    Miguel  29.0        Sev     miguel@mail.com     2024-06-01
8      Juan   NaN     madrid      juan@@mail.com     2024-02-30
9     Laura  31.0   Valéncia   laura@example.com     2024-07-10
10  Antonio  35.0     Madrid    antonio@mail.com     2023-11-25
11    María   NaN    Sevilla      maria@mail.com     2024-01-15
12     Raúl   NaN   Valencia   raul@@example.com     2024-05-12
13      Eva  28.0  barcelona         eva@example     2024-04-05
14   Daniel  33.0     Madrid  daniel@example.com     2024-02-29
15   Isabel  27.0       Sev.     isabel@mail.com     2024-03-10
16  Alberto  40.0   Valencia    alberto@mail.com     2024/06/12
17   Carmen   NaN   Valéncia  carmen@example.com     2024-07-01
18    Pablo  19.0     MADRID       pablo@mailcom     2024-05-30
19   Teresa  25.0   Sevilla     teresa@ mail.com     2024-02-20

In [11]:
df["edad"] = df["edad"].fillna(df["edad"].mean())

In [12]:
df

     nombre       edad     ciudad               email fecha_registro
0       Ana  25.000000    madrid      ana@example.com     2024-01-10
1      Luis  30.000000    Sevilla    luis(at)mail.com     10/01/2024
2     Marta  28.285714   VALENCIA   marta@example.com     2024-02-15
3     Pedro  28.285714  Barcelona    pedroexample.com            NaN
4     Lucía  22.000000     Madrid   lucia@example.com      2024-3-05
5       Ana  25.000000        MAD     ana@example.com     2024/01/10
6     Sofia  27.000000    sevilla                 NaN     2024-05-20
7    Miguel  29.000000        Sev     miguel@mail.com     2024-06-01
8      Juan  28.285714     madrid      juan@@mail.com     2024-02-30
9     Laura  31.000000   Valéncia   laura@example.com     2024-07-10
10  Antonio  35.000000     Madrid    antonio@mail.com     2023-11-25
11    María  28.285714    Sevilla      maria@mail.com     2024-01-15
12     Raúl  28.285714   Valencia   raul@@example.com     2024-05-12
13      Eva  28.000000  barcelona         eva@example     2024-04-05
14   Daniel  33.000000     Madrid  daniel@example.com     2024-02-29
15   Isabel  27.000000       Sev.     isabel@mail.com     2024-03-10
16  Alberto  40.000000   Valencia    alberto@mail.com     2024/06/12
17   Carmen  28.285714   Valéncia  carmen@example.com     2024-07-01
18    Pablo  19.000000     MADRID       pablo@mailcom     2024-05-30
19   Teresa  25.000000   Sevilla     teresa@ mail.com     2024-02-20

- Todas las ciudades estén escritas en mayúsculas

In [13]:
df["ciudad"] = df["ciudad"].str.upper()

In [14]:
df

     nombre       edad     ciudad               email fecha_registro
0       Ana  25.000000    MADRID      ana@example.com     2024-01-10
1      Luis  30.000000    SEVILLA    luis(at)mail.com     10/01/2024
2     Marta  28.285714   VALENCIA   marta@example.com     2024-02-15
3     Pedro  28.285714  BARCELONA    pedroexample.com            NaN
4     Lucía  22.000000     MADRID   lucia@example.com      2024-3-05
5       Ana  25.000000        MAD     ana@example.com     2024/01/10
6     Sofia  27.000000    SEVILLA                 NaN     2024-05-20
7    Miguel  29.000000        SEV     miguel@mail.com     2024-06-01
8      Juan  28.285714     MADRID      juan@@mail.com     2024-02-30
9     Laura  31.000000   VALÉNCIA   laura@example.com     2024-07-10
10  Antonio  35.000000     MADRID    antonio@mail.com     2023-11-25
11    María  28.285714    SEVILLA      maria@mail.com     2024-01-15
12     Raúl  28.285714   VALENCIA   raul@@example.com     2024-05-12
13      Eva  28.000000  BARCELONA         eva@example     2024-04-05
14   Daniel  33.000000     MADRID  daniel@example.com     2024-02-29
15   Isabel  27.000000       SEV.     isabel@mail.com     2024-03-10
16  Alberto  40.000000   VALENCIA    alberto@mail.com     2024/06/12
17   Carmen  28.285714   VALÉNCIA  carmen@example.com     2024-07-01
18    Pablo  19.000000     MADRID       pablo@mailcom     2024-05-30
19   Teresa  25.000000   SEVILLA     teresa@ mail.com     2024-02-20

- Todos los emails tengan el formato correcto (texto@otrotexto.com)

In [15]:
df = df[df["email"].str.contains(r"^[\w\.-]+@[\w\.-]+\.\w+$", na=False)]

In [16]:
df

     nombre       edad    ciudad               email fecha_registro
0       Ana  25.000000   MADRID      ana@example.com     2024-01-10
2     Marta  28.285714  VALENCIA   marta@example.com     2024-02-15
4     Lucía  22.000000    MADRID   lucia@example.com      2024-3-05
5       Ana  25.000000       MAD     ana@example.com     2024/01/10
7    Miguel  29.000000       SEV     miguel@mail.com     2024-06-01
9     Laura  31.000000  VALÉNCIA   laura@example.com     2024-07-10
10  Antonio  35.000000    MADRID    antonio@mail.com     2023-11-25
11    María  28.285714   SEVILLA      maria@mail.com     2024-01-15
14   Daniel  33.000000    MADRID  daniel@example.com     2024-02-29
15   Isabel  27.000000      SEV.     isabel@mail.com     2024-03-10
16  Alberto  40.000000  VALENCIA    alberto@mail.com     2024/06/12
17   Carmen  28.285714  VALÉNCIA  carmen@example.com     2024-07-01

- Todas las fechas estén en formato DD/MM/AAAA.

In [20]:
df["fecha_registro"] = pd.to_datetime(df["fecha_registro"], errors="coerce")

In [21]:
df

     nombre       edad    ciudad               email fecha_registro fecha
0       Ana  25.000000   MADRID      ana@example.com     2024-01-10  None
2     Marta  28.285714  VALENCIA   marta@example.com     2024-02-15  None
4     Lucía  22.000000    MADRID   lucia@example.com     2024-03-05  None
5       Ana  25.000000       MAD     ana@example.com            NaT  None
7    Miguel  29.000000       SEV     miguel@mail.com     2024-06-01  None
9     Laura  31.000000  VALÉNCIA   laura@example.com     2024-07-10  None
10  Antonio  35.000000    MADRID    antonio@mail.com     2023-11-25  None
11    María  28.285714   SEVILLA      maria@mail.com     2024-01-15  None
14   Daniel  33.000000    MADRID  daniel@example.com     2024-02-29  None
15   Isabel  27.000000      SEV.     isabel@mail.com     2024-03-10  None
16  Alberto  40.000000  VALENCIA    alberto@mail.com            NaT  None
17   Carmen  28.285714  VALÉNCIA  carmen@example.com     2024-07-01  None

In [22]:
df["fecha_registro"] = df["fecha_registro"].dt.strftime('%d/%m/%Y')

In [23]:
df = df.drop(columns=["fecha"])

In [24]:
df

     nombre       edad    ciudad               email fecha_registro
0       Ana  25.000000   MADRID      ana@example.com     10/01/2024
2     Marta  28.285714  VALENCIA   marta@example.com     15/02/2024
4     Lucía  22.000000    MADRID   lucia@example.com     05/03/2024
5       Ana  25.000000       MAD     ana@example.com            NaN
7    Miguel  29.000000       SEV     miguel@mail.com     01/06/2024
9     Laura  31.000000  VALÉNCIA   laura@example.com     10/07/2024
10  Antonio  35.000000    MADRID    antonio@mail.com     25/11/2023
11    María  28.285714   SEVILLA      maria@mail.com     15/01/2024
14   Daniel  33.000000    MADRID  daniel@example.com     29/02/2024
15   Isabel  27.000000      SEV.     isabel@mail.com     10/03/2024
16  Alberto  40.000000  VALENCIA    alberto@mail.com            NaN
17   Carmen  28.285714  VALÉNCIA  carmen@example.com     01/07/2024